version: '3.8'

services:
   app:
      build: .
      ports:
         - '8085:8085'
      volumes:
         - .:/usr/src/app
      environment:
         NODE_ENV: production
      command: ['npm', 'start']
